version: "3"
services:
  db:
    image: 'mysql:5.7'
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
       - /opt/test:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment: 
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: timesheetdevops
    ports:
      - '3307:3308'
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      
  web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - /target/timesheet_devops.war:/usr/local/tomcat/webapps/timesheet_devops.war
    ports:
      - '8085:8088'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheetdevops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      

      
    