version: "3"
services:
  db:
    image: 'mysql:5.7.31'
    restart : unless-stopped
    volumes:
      - /opt/test:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3308
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '81:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      
  web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./target/timesheet_devops.war
    ports:
      - '8085:8088'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheetdevops
      MYSQL_USER: root
      

      
    